name: appdownloader
description: An empty Aqueduct application.
version: 0.0.1
author: leejoker <liang91123@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  html: ^0.14.0+3

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0